<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contoso.Lending.Domain\Contoso.Lending.Domain.csproj" />
    <ProjectReference Include="..\Contoso.Lending.Data\Contoso.Lending.Data.csproj" />
  </ItemGroup>

</Project>
